### ISSUE TITLE
Error using mex

### ISSUE THREAD

**Issue by c185scmyw** [Kartz4code/pNMPC_CODEGEN#2]
Hi, there is a problem when set the constraint of p1 to be [0, 1] in Main.m, and change "ControlParameterization(p1, 'Linear', 5, -umax, umax);" to  "ControlParameterization(p1, 'Piecewise', 5, 0, umax);".  this error says:
pNMPC_CODEGEN-master\Source.cpp(50): error C2440:
Error using mex
Source.cpp
C:\Users\Documents\GitHub\pNMPC_CODEGEN-master\Source.cpp(50): error C2440:
'initializing': cannot convert from 'initializer list' to 'ControlParamZ<Piecewise>'
C:\Users\Documents\GitHub\pNMPC_CODEGEN-master\Source.cpp(50): note: No constructor could
take the source type, or constructor overload resolution was ambiguous
Error in generateSFUNC (line 58)
eval(['mex ' MATLAB_INTERFACE_FLAG ' ' INCLUDE ' ' OBJ])

Error in Main (line 92)
generateSFUNC('CRANE2D');

Thank you very much!

**Comment by Kartz4code** [comment]
Hi, Thanks again for pointing this out, this looks like a type conversion issue. I would recommend you to use a number with tolerance like 0.0000001 rather than 0 for the time being. I will look into it and fix it!.
